### ISSUE TITLE
Link to https://bfinster-value-stream-map.netlify.app/ in the GH key info box (settings)?

### ISSUE THREAD

**Issue by paul-hammant** [bdfinst/value-stream-map#11]

**Comment by bdfinst** [comment]
Not sure what you mean.

**Comment by paul-hammant** [comment]
Just here - link back to finished site -

![image](https://user-images.githubusercontent.com/82182/108431573-f3ddc880-723a-11eb-8af5-f0379a0f3aac.png)

**Comment by bdfinst** [comment]
Done
